spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryManagementSystem?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true